contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #assemblers channel"
    url: https://nfcore.slack.com/channels/assemblers
    about: Discussion about the nf-core/assemblers pipeline
